// AngularJS/DropWeb/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor ( private httpClient: HttpClient ) { }

  postProfile() {
    this.httpClient.post('178.62.39.172', {
        name: 'mark',
        age: 21
      })
      .subscribe(
        (data: any ) => {
          console.log(data);
        }
      );
  }
}


<div id="divHeader">
  <!--<h1 id="title">Drop</h1>-->
  <img src="assets/Drop_logo.png" alt="logo" id="logoImg">
</div>





<div id="DropDiv">

</div>

<div id="CentreDiv">

  <form id="addButton" action="upload.php" method="post" enctype="multipart/form-data">
    <input type="file" name="fileToUpload" id="fileToUpload">
    <!--<input type="submit" value="Upload Image" name="submit">-->
  </form>
  <input id="text" type="text" value="123456" style="width:80%" />
  <br />
  <div id="QRCode">
    <p>
      <qr text=" '1122222211' " type-number="typeNumber" correction-level="correctionLevel" size="size" input-mode="inputMode" image="image"></qr>
    </p>
  </div>

</div>

<div id="barBottom"></div>

<script src="../qrFiles/lib/qrcode.js"></script>
<script src="../qrFiles/src/angular-qr.js"></script>

<script>
  angular.module('adaptiveApp', ['ja.qr']).

  controller('AdaptiveCtrl', function ($scope) {
    $scope.qrcodeString = 'YOUR TEXT TO ENCODE';
    $scope.size = 250;
    $scope.correctionLevel = '';
    $scope.typeNumber = 0;
    $scope.inputMode = '';
    $scope.image = true;
  });
</script>

// React/react-app/src/App.js
import React from 'react';
import './App.css';

class App extends React.Component{
    constructor() {
        super();
        this.state = {
            txt: 'this is the state txt'
        }
    }
    update(e){
        this.setState({txt: e.target.value})
    }

    render(){
        return (
            <div>
                <div id="divHeader">

                    <img src="Drop_logo.png" alt="logo" id="logoImg"></img>
                </div>


                <div id="barBottom">

                </div>


                <div id="DropDiv">

                </div>

                <div id="CentreDiv">

                    <form id="addButton" action="upload.php" method="post" enctype="multipart/form-data">
                        <input type="file" name="fileToUpload" id="fileToUpload"></input>

                    </form>
                    <input id="text" type="text" value="123456" style="width:80%" />
                    <br />
                    <div id="QRCode"></div>
                </div>
            </div>

        )
    }
}

export default App;
